<a href="https://colab.research.google.com/github/moonsunglab/BigData_study/blob/main/Machine_Learning/ml01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 고급기능

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# np.ndarray 속성

In [ ]:
arr = np.ones(shape=(2, 3))

In [ ]:
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr.shape  # shape 속성: 배열의 각 축(axis)을 따라서 있는 원소의 개수들의 tuple.

(2, 3)

In [ ]:
arr.dtype  # dtype 속성: 배열 원소의 데이터 타입.

dtype('float64')

In [ ]:
arr.size  # size 속성: 배열의 모든 원소 개수.

6

In [ ]:
arr.ndim  # ndim: 배열의 차원(dimension). 배열의 축(axis)의 개수.

2

In [ ]:
arr = np.arange(10)  # 0 이상 10 미만의 (10개의) 정수들로 이루어진 배열.

In [ ]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print('dtyp:', arr.dtype)
print('ndim:', arr.ndim)
print('shape:', arr.shape)
print('size:', arr.size)

dtyp: int64
ndim: 1
shape: (10,)
size: 10


In [ ]:
arr = np.arange(1, 25).reshape((2, 3, 4))

In [ ]:
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
print('dtyp:', arr.dtype)
print('ndim:', arr.ndim)
print('shape:', arr.shape)
print('size:', arr.size)

dtyp: int64
ndim: 3
shape: (2, 3, 4)
size: 24


# Indexing

인덱스를 사용해서 배열 원소를 참조.

In [ ]:
print(arr)  #> 3d array(3차원 배열)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
print(arr[0])  #> 2d array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(arr[0, 0])  #> 1d array

[1 2 3 4]


In [ ]:
print(arr[0][0])

[1 2 3 4]


In [ ]:
print(arr[0, 0, 0])  #> int -> 스칼라(scalar)

1


In [ ]:
print(arr[0][0][0])

1


*   Python list 인덱스 사용 방법:
    *   `list[i][j][k]...`
*   NumPy ndarray 인덱스 사용 방법:
    *   `array[i, j, k, ...]`
    *   `array[i][j][k]...`

# Slicing

## 1차원 배열의 slicing

In [ ]:
np.random.seed(1)
arr = np.random.randint(100, size=10)  # [0, 100) 범위의 정수 난수 10개로 이루어진 1d array.

In [ ]:
print(arr)

[37 12 72  9 75  5 79 64 16  1]


In [ ]:
print(arr[1:5])

[12 72  9 75]


In [ ]:
print(arr[:3])  #> 시작 인덱스 0은 생략 가능

[37 12 72]


In [ ]:
print(arr[-3:])  #> 배열의 끝까지 자를 때는 마지막 인덱스는 생략 가능.
# 배열의 끝에서부터 거꾸로 매기는 인덱스는 음수 인덱스.

[64 16  1]


In [ ]:
print(arr[0:1])  #> slicing의 결과 -> 배열
print(arr[0])    #> indexing의 결과 -> 원소(스칼라)

[37]
37


## 2차원 배열의 slicing

In [ ]:
arr = np.arange(1, 21).reshape((4, 5))

In [ ]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
# 2차원 배열 arr의 첫 2개의 1차원 배열
# print(arr[:2])
print(arr[:2, :])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# 2차원 배열 arr의 마지막 2개의 1차원 배열
# print(arr[-2:])
print(arr[-2:, :])

[[11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
print(arr[:2, :3])

[[1 2 3]
 [6 7 8]]


In [ ]:
print(arr[1:3, 1:4])

[[ 7  8  9]
 [12 13 14]]


In [ ]:
print(arr[1:3][1:4])  # 위쪽 셀의 결과와 비교!

[[11 12 13 14 15]]


## 3차원 배열의 slicing

In [ ]:
arr = np.arange(1, 61).reshape((3, 4, 5))

In [ ]:
print(arr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]


In [ ]:
print(arr[:2])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]]


In [ ]:
print(arr[:2, :, :])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]]


In [ ]:
# print(arr[:2, :2, :])
print(arr[:2, :2])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]


In [ ]:
print(arr[:2, :2, :2])

[[[ 1  2]
  [ 6  7]]

 [[21 22]
  [26 27]]]


In [ ]:
print(arr[:1, :, :])  #> 결과: 3d array

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]]


In [ ]:
print(arr[0, :, :])  #> 결과: 2d array

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# Shape(모양) 변경

*   `np.ndarray.reshape(arg)`
*   `np.ndarray.ravel()`
*   `np.ndarray.flatten()`
*   `np.newaxis` 속성

## reshape

In [ ]:
arr_1d = np.arange(12)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# arr_1d를 (4, 3) shape의 2d array로 변환
arr_2d = arr_1d.reshape((4, 3))
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
# reshape 메서드의 아규먼트를 전달할 때 자동으로 계산할 수 있는 차원의 값은 -1을 사용할 수 있음.
arr_2d = arr_1d.reshape((4, -1))  #> (4, 3)
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
arr_2d = arr_1d.reshape((-1, 4))  #> (3, 4)
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# 2차원 배열 arr_2d를 1차원 배열로 변환.
result = arr_2d.reshape((3 * 4,))
print(result)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
result = arr_2d.reshape((-1,))
print(result)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
arr_1d = np.arange(60)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]


In [ ]:
# 1차원 배열 arr_1d의 모양을 (3, 4, 5)로 변환
result = arr_1d.reshape((3, 4, -1))  # (3, 4, 5)
print(result)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [ ]:
# 1차원 배열 arr_1d의 모양을 (5, 4, 3)로 변환
result = arr_1d.reshape((5, 4, -1))
print(result)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]

 [[48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]]


## ravel vs flatten

*   flatten
    *   n차원 배열 ndarray를 1차원 배열로 변환한 "복사본"을 리턴.
    *   원본 배열과는 별개의 새로운 배열을 메모리에 만들어서 리턴.
*   ravel
    *   n차원 배열 ndarray를 1차원 배열로 변환한 "뷰(view)"를 리턴.
    *   별개의 새로운 배열을 만드는 것이 아니라, 원본 배열의 모양을 1차원으로 보여줄 뿐.

In [ ]:
arr_2d = np.arange(12).reshape((3, 4))
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
flattened = arr_2d.flatten()
print(flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
flattened[0] = 123  #> 1차원 배열 flattened의 첫번째 위치에 새로운 값을 재할당.
print(flattened)

[123   1   2   3   4   5   6   7   8   9  10  11]


In [ ]:
print(arr_2d)  # 원본 2차원 배열과는 무관.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
raveled = arr_2d.ravel()
print(raveled)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
raveled[0] = 123  # 1차원 배열의 원소를 변경
print(raveled)

[123   1   2   3   4   5   6   7   8   9  10  11]


In [ ]:
print(arr_2d)  # 원본 2차원 배열의 값을 변경!

[[123   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


## `np.newaxis` 속성을 사용한 차원 늘리기

In [ ]:
arr = np.arange(1, 6)
print(arr)

[1 2 3 4 5]


In [ ]:
arr.shape  #> (5,)

(5,)

In [ ]:
result = arr[np.newaxis, :]
print(result)

[[1 2 3 4 5]]


In [ ]:
result.shape  #> (1, 5)

(1, 5)

In [ ]:
result = arr[:, np.newaxis]
print(result)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
result.shape  #> (5, 1)

(5, 1)

In [ ]:
print(arr_2d)  #> shape: (3, 4)

[[123   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [ ]:
result = arr_2d[np.newaxis, :, :]
print(result)

[[[123   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]]


In [ ]:
result.shape  #> (1, 3, 4)

(1, 3, 4)

In [ ]:
result = arr_2d[:, :, np.newaxis]
print(result)

[[[123]
  [  1]
  [  2]
  [  3]]

 [[  4]
  [  5]
  [  6]
  [  7]]

 [[  8]
  [  9]
  [ 10]
  [ 11]]]


In [ ]:
result.shape  #> (3, 4, 1)

(3, 4, 1)

In [ ]:
result = arr_2d[:, np.newaxis, :]
print(result)

[[[123   1   2   3]]

 [[  4   5   6   7]]

 [[  8   9  10  11]]]


In [ ]:
result.shape

(3, 1, 4)

In [ ]:
print(arr)

[1 2 3 4 5]


In [ ]:
result = arr[:, np.newaxis, np.newaxis]
print(result)

[[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]]


In [ ]:
result.shape

(5, 1, 1)

In [ ]:
arr_2d

array([[123,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [ ]:
arr_2d[np.newaxis, :]

array([[[123,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]]])

# concatenate

*   `np.concatenate([array1, array2, ...], axis=0)`: 특정 축(axis) 방향으로 배열 이어붙이기.
*   `np.r_[array1, array2]`: 행들을 이어붙이기. axis=0 방향으로 이어붙이기.
*   `np.c_[array1, array2]`: 컬럼들을 이어붙이기. axis=1 방향으로 이어붙이기.

In [ ]:
# (2, 3) shape의 2d array
arr1 = np.arange(1, 7).reshape((2, 3))
print(arr1)

[[1 2 3]
 [4 5 6]]


In [ ]:
# (1, 3) shape의 2d array
arr2 = np.array([[7, 8, 9]])
print(arr2)

[[7 8 9]]


In [ ]:
# (2, 1) shape의 2d array
arr3 = np.array([[10], [11]])
print(arr3)

[[10]
 [11]]


In [ ]:
result = np.concatenate([arr1, arr2])  # axis=0 생략 가능(기본값)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
np.r_[arr1, arr2]  # arr1과 arr2가 2d array일 때 concatenate를 간단히.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
result = np.concatenate([arr1, arr3], axis=1)
print(result)

[[ 1  2  3 10]
 [ 4  5  6 11]]


In [ ]:
np.c_[arr1, arr3]  # arr1과 arr3이 2d array일 때 concatenate를 간단히.

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11]])

# Broadcasting

*   np.ndarray의 연산(+, -, *, /, //, %, >, <, ==, ...)은 같은 위치(인덱스)의 원소들끼리(elementwise) 연산이 수행됨.
*   서로 모양(shape)이 다른 배열들끼리 연산이 가능한 경우가 있음(broadcast가 가능한 경우)


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
print(a + b)

[5 7 9]


In [ ]:
c = np.array([7, 8])
# print(a + c)
#> ValueError: (3,) shape의 1d array와 (2,) shape의 1d array는 서로 연산을 할 수 없음.

## ndarray와 scalar의 연산

항상 broadcast가 가능. 항상 연산이 가능. 스칼라를 배열의 각 원소마다 연산 수행.

In [ ]:
print(a + 10)

[11 12 13]


## 2d array와 1d array 또는 2d array에서의 broadcast

In [ ]:
a = np.arange(1, 7).reshape((2, 3))  # shape: (2, 3)
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
b = np.array([7, 8, 9])  # shape: (3,)
print(b)

[7 8 9]


In [ ]:
# (3,) shape의 1d array -> (1, 3) shape 2d array -> (2, 3) shape으로 broadcast
print(a + b)

[[ 8 10 12]
 [11 13 15]]


In [ ]:
b = np.array([[5], [10]])  # shape: (2, 1)
print(b)

[[ 5]
 [10]]


In [ ]:
# (2, 1) shape의 2d array -> (2, 3) shape으로 broadcast
print(a + b)

[[ 6  7  8]
 [14 15 16]]


broadcasting이 가능한 경우:

*   브로드캐스팅은 누락되거나 길이가 1인 차원에 대해서만 수행.
*   이어지는 차원의 축이 길이가 같은 경우 브로드캐스팅이 가능.


## broadcast 활용

*   표준화(standardization): 배열의 평균이 0이 되고, 표준편차가 1이 되도록 값들을 변환.
*   정규화(normalization): 최솟값이 0이 되고 최댓값이 1이 되도록 값들을 변환.

### 표준화

In [ ]:
x = np.array([1, 2, 3, 4, 5])

In [ ]:
mu = x.mean()  # 평균, np.mean(x)
print(mu)

3.0


In [ ]:
sigma = x.std()  # 표준편차, np.std(x)
print(sigma)

1.4142135623730951


In [ ]:
x_scaled = (x - mu) / sigma
print(x_scaled)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
np.mean(x_scaled)

np.float64(0.0)

In [ ]:
np.std(x_scaled)

np.float64(0.9999999999999999)

### 정규화

In [ ]:
x_min = np.min(x)  # 배열 x의 최솟값
x_max = np.max(x)  # 배열 x의 최댓값
print(x_min, x_max)

1 5


In [ ]:
x_scaled = (x - x_min) / (x_max - x_min)
print(x_scaled)

[0.   0.25 0.5  0.75 1.  ]


### 2차원 배열에서 표준화, 정규화

In [ ]:
# (3, 2) shape 2d array
X = np.arange(1, 7).reshape((3, 2))
print(X)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# 표준화
X_scaled = (X - np.mean(X)) / np.std(X)
print(X_scaled)

[[-1.46385011 -0.87831007]
 [-0.29277002  0.29277002]
 [ 0.87831007  1.46385011]]


In [ ]:
# 정규화
X_scaled = (X - np.min(X)) / (np.max(X) - np.min(X))
print(X_scaled)

[[0.  0.2]
 [0.4 0.6]
 [0.8 1. ]]


In [ ]:
np.mean(X, axis = 0, keepdims =True)

array([[3., 4.]])

In [ ]:
np.mean(X, axis = 1, keepdims= True)

array([[1.5],
       [3.5],
       [5.5]])

axis = 0 축 방향으로 표준화

In [ ]:
X_scaled = (X - np.mean(X,axis = 0, keepdims=True)) / np.std(X, axis=0, keepdims=True)
print(X_scaled)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


axis = 1 축 방향으로 표준화

In [ ]:
X_scaled = (X - np.mean(X,axis = 1, keepdims=True)) / np.std(X, axis=1, keepdims=True)
print(X_scaled)

[[-1.  1.]
 [-1.  1.]
 [-1.  1.]]


axis = 0 축 방향으로 표준화

In [ ]:
X_min = np.min(X, axis = 0, keepdims= True)
X_max = np.max(X , axis = 0, keepdims= True)
X_scaled = (X - X_min) / (X_max - X_min)
print(X_scaled)

[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


### seaborn 모듈에서 iris 데이터셋을 로드, 표준화.

In [ ]:
ir = sns.load_dataset('iris')

In [ ]:
ir.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
ir.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
sl_min = np.min(ir.sepal_length)
sl_min

4.3

In [ ]:
sl_max = np.max(ir.sepal_length)
sl_max

7.9

In [ ]:
sw_min = np.min(ir.sepal_width)
sw_min

2.0

In [ ]:
sw_max = np.max(ir.sepal_width)
sw_max

4.4

In [ ]:
pl_min = np.min(ir.petal_length)
pl_min

1.0

In [ ]:
pl_max = np.max(ir.petal_length)
pl_max

6.9

In [ ]:
pw_min = np.min(ir.petal_width)
pw_min

0.1

In [ ]:
pw_max = np.max(ir.petal_width)
pw_max

2.5

#### 오쌤방법

In [ ]:
ir.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
# ir DataFrame에서 Species컬럼 삭제
ir_ft = ir.drop(columns= 'species')

In [ ]:
ir_ft.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [ ]:
# DataFrame.values 속성 -> DataFrame의 값들을 ndarray로 저장한 속성.
X = ir_ft.values

In [ ]:
X[:5,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

axis = 0 표준화(평균 = 0, 표준편차 = 1)

In [ ]:
mu = np.mean(X, axis = 0, keepdims = True)

In [ ]:
mu

array([[5.84333333, 3.05733333, 3.758     , 1.19933333]])

In [ ]:
sigma = np.std(X, axis = 0, keepdims= True)

In [ ]:
sigma

array([[0.82530129, 0.43441097, 1.75940407, 0.75969263]])

In [ ]:
X_std =  (X - mu) / sigma

In [ ]:
X_std[:5,:]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])

axis = 0 축을 따라서 정규화(최솟값 = 0, 최댓값 = 1)

In [ ]:
X_min = np.min(X, axis = 0, keepdims = True)

In [ ]:
X_min

array([[4.3, 2. , 1. , 0.1]])

In [ ]:
X_max = np.max(X,axis = 0, keepdims= True)

In [ ]:
X_max

array([[7.9, 4.4, 6.9, 2.5]])

In [ ]:
X_norm = (X - X_min) / (X_max - X_min)

In [ ]:
X_norm[:5, :]

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667]])

# 행렬 곱(matrix multiplication)

*   `@` 연산자: 1차원 배열, 2차원 배열에서 사용 가능.
*   `np.matmul()` 함수: n차원 배열에서 사용 가능.

## 1차원 배열의 행렬 곱

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
print(a)

[1 2 3]


In [ ]:
print(b)

[4 5 6]


In [ ]:
a @ b

np.int64(32)

In [ ]:
np.matmul(a,b)

np.int64(32)

## 2차원 배열의 행렬 곱
`(i,j) @ (j,k) -> (i,k)`

In [ ]:
A = np.arange(1,7).reshape(2,3)
print(A)

[[1 2 3]
 [4 5 6]]


In [ ]:
B = np.ones(shape=(3,2), dtype = np.int64)
print(B)

[[1 1]
 [1 1]
 [1 1]]


In [ ]:
A@B

array([[ 6,  6],
       [15, 15]])

In [ ]:
np.matmul(A,B)

array([[ 6,  6],
       [15, 15]])

In [ ]:
A = np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
B = np.array([
    [1,1],
    [2,2],
    [1,2],
    [2,3]
])
print(B)

[[1 1]
 [2 2]
 [1 2]
 [2 3]]


In [ ]:
A @ B

array([[16, 23],
       [40, 55],
       [64, 87]])

## 2차원 배열과 1차원 배열에서의 행렬 곱

```
(i,j) @ (j,) -> (i,)        # 2D array @ 1D array -> 1D array
(i,j) @ (j,1) -> (i,1)      # 2D array @ 2D array -> 2D array
```

In [ ]:
A = np.arange(1,7).reshape(2,3)
print(A)

[[1 2 3]
 [4 5 6]]


In [ ]:
b = np.arange(1,4)
print(b)

[1 2 3]


In [ ]:
A @ b

array([14, 32])

In [ ]:
np.matmul(A,b)

array([14, 32])

In [ ]:
B = b.reshape(3,-1)
print(B)

[[1]
 [2]
 [3]]


In [ ]:
A @ B

array([[14],
       [32]])

In [ ]:
np.matmul(A,B)

array([[14],
       [32]])